# Generated by Django 4.0.6 on 2022-07-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
